name: Relatório de erros
description: Algo não está funcionando muito bem no software.
labels: [not confirmed]
body:
- type: markdown
  attributes:
    value: |
      Os relatórios de erros só devem ser usados para relatar problemas com a forma como o software funciona. Para assistência na instalação deste software, bem como na depuração de problemas com dependências, favor utilizar nosso [Servidor do Discord].(https://discord.gg/68k7wDGjYc).

- type: textarea      
  attributes:
    label: Comportamento atual
    description: Favor fornecer uma descrição clara e concisa da questão.
  validations:
    required: true

- type: textarea      
  attributes:
    label: Comportamento esperado
    description: Por favor, descreva o que você esperava que acontecesse.
  validations:
    required: true

- type: textarea      
  attributes:
    label: Passos para Reproduzir
    description: Por favor, seja o mais detalhado possível ao fornecer passos para a reprodução, a falha em fornecer passos resultará no fechamento desta questão.
  validations:
    required: true

- type: input
  id: panel-version
  attributes:
    label: Versão do painel
    description: Número da versão do seu Painel (a última não é uma versão)
    placeholder: 3.0.0
  validations:
    required: true

- type: input
  id: wings-version
  attributes:
    label: Versão da Wings
    description: Número da versão de suas Asas (a última não é uma versão)
    placeholder: 1.4.2
  validations:
    required: true
  

- type: textarea
  id: panel-logs
  attributes:
    label: Logs de erros
    description: |
      Execute o seguinte comando para coletar logs em seu sistema.
      
      Wings: `sudo wings diagnostics`
      Panel: `tail -n 100 /var/www/jexactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`
    placeholder: "https://bin.ptdl.co/a1h6z"
    render: bash
  validations:
    required: false
    
- type: checkboxes
  attributes:
    label: Existe algum problema para isso?
    description: Por favor [pesquisar aqui](https://github.com/Next-Panel/Jexactyl-BR/issues) para ver se já existe um problema para o seu problema.
    options:
    - label: Pesquisei as questões existentes antes de abrir este assunto.
      required: true
    - label: Eu verifiquei no servidor Discord e acredito que este é um bug com o software, e não um problema de configuração com meu sistema específico.
      required: true
