name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ["8.0", "8.1"]

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --no-check-version

    - name: Install dependencies
      run: composer install --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit --no-coverage
